### ISSUE TITLE
Tasks for July

### ISSUE THREAD

**Issue by aditya4d** [ROCm/AMDMIGraphX#16]
This is a ToDo lists to finish for July. Instead of creating an issue for each task, lets keep one for each release or month and discuss them
@adityaatluri
- [ ] Add batch norm cpu implementation for both inference and training along with tests.
- [ ] Add GPU kernel for batch norm for both inference and training along with tests.
- [ ] Add AMD copyright to all files and MIT license

@pfultz2 

@wsttiger
