### ISSUE TITLE
Ensure MIGX ORT EP works with MI300

### ISSUE THREAD

**Issue by causten** [ROCm/AMDMIGraphX#2078]
Do an end to end build and run with the MIGraphX EP on an MI300 system.

**Comment by TedThemistokleous** [comment]
Plan is to to do the following once I've acquired access

- [ ] Build MIGraphX & onnxruntime (standalone) + unit tests 
- [ ] DLM run for resnet50 onnxrt example  (blocked by #2047 )
- [ ] DLM  run of gelu, layernorm and attention parity (transformers checks)
- [ ] DLM run of bert models (distil bert, bert base cased)

**Comment by TedThemistokleous** [comment]
Able to build with onnxruntime and MIGraphX on a 6.0 container. Seeing errors with unit tests

**Comment by TedThemistokleous** [comment]
Fixed builds with the following settings

- used onnxruntime fork:https://github.com/ROCmSoftwarePlatform/onnxruntime |
     internal branch rocm5.7_internal_testing_gfx940

- Had to modify our build_and_test script to add additional flags found in : https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/2115/files

Will cleanup the above PR once ROCm issues resolve. Will begin to run DLM for now

**Comment by TedThemistokleous** [comment]
Dropping artifacts here for our runs. Running into last issues with some of the bert distilled and bert large models

[gpt2_results.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423266/gpt2_results.log)
[parity_gelu_migx.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423268/parity_gelu_migx.log)
[parity_layernorm_migx.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423269/parity_layernorm_migx.log)
[party_huggingface_gpt_attention.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423270/party_huggingface_gpt_attention.log)
[perf_migx_bert_distilled_benchmarks.csv](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423271/perf_migx_bert_distilled_benchmarks.csv)
[perf_migx_gpt2.csv](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423272/perf_migx_gpt2.csv)

**Comment by TedThemistokleous** [comment]
[benchmark_summary_20230823-221927.csv](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423763/benchmark_summary_20230823-221927.csv)
[perf_migx_bert_distilled_benchmarks.csv](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423764/perf_migx_bert_distilled_benchmarks.csv)
[perf_migx_conv_to_onnx_benchmarks.csv](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423765/perf_migx_conv_to_onnx_benchmarks.csv)
[perf_migx_onnxrt_distil.csv](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/12423766/perf_migx_onnxrt_distil.csv)
